-- Twitch 帳號已不存在的 166 列標為 removed（2026-10-02）
--
-- 這些列都來自 2026-07-06 匯入的外部名單（TaiwanVTuberTrackingData），只有 login、沒有 broadcaster id，
-- 從未驗證（verified = false）。2026-10-02 以 helix/users?login= 與 helix/search/channels（完全同名）兩種方式查，
-- 對照組正常、兩者皆 0／166：帳號已刪除、停權或改名，週表永遠無法追蹤，前台的 Twitch 連結也是死連結。
-- 只改 vtuber_channels.status；vtubers.twitch_channel_id（舊欄位）不動。
-- 只動 status = 'active' 且 external_id 為空的列（依 handle 不分大小寫）；已補上 id 的不會被誤改。
--
-- 回滾（用套用前的備份）：
--   update public.vtuber_channels c set status = b.status, updated_at = now()
--   from backup.twitch_dead_logins_before_20261002 b where b.id = c.id and c.status is distinct from b.status;

create schema if not exists backup;
create table if not exists backup.twitch_dead_logins_before_20261002 as
    select id, vtuber_id, handle, external_id, status, updated_at from public.vtuber_channels
    where platform = 'twitch' and status = 'active' and external_id is null;

update public.vtuber_channels c
set status = 'removed',
    updated_at = now()
from (values
    ('16ichiroku61'),
    ('46shizuru'),
    ('713_channel'),
    ('ach471123'),
    ('acs166'),
    ('ailywanderwulf'),
    ('ainodayo717'),
    ('aka6120'),
    ('amarantha302876'),
    ('ansei_v'),
    ('anstone5769'),
    ('aralyn_vtuber'),
    ('arthurblue5566'),
    ('arubychannel'),
    ('axixxaxi'),
    ('ayame_spector_29'),
    ('baiyuge921'),
    ('boniya0w0'),
    ('boxhead1005'),
    ('bridget013'),
    ('chengmimeow'),
    ('chimei0405'),
    ('chiveswang_llt5'),
    ('chloelancemay'),
    ('choxout'),
    ('crucis_sf'),
    ('da_way_lu_yu'),
    ('darknightconei'),
    ('demon_cat_noah'),
    ('doson0606'),
    ('dubistowch'),
    ('eeewdoog'),
    ('elinoralumiere'),
    ('ellise_aepro'),
    ('elyana_tenshi'),
    ('ena97138'),
    ('enchan_2018'),
    ('enola_vtb'),
    ('enominya_andi'),
    ('erica220724'),
    ('erica3940'),
    ('eroi_moon'),
    ('etsukura_konatou'),
    ('fafa_vtb'),
    ('famy_0402'),
    ('fuyuhiro_vtuber'),
    ('garicheach'),
    ('getsuka1008'),
    ('ggsunbeam'),
    ('greenraisa'),
    ('hanabi_lumen'),
    ('hanasaki_vtuber'),
    ('hanekawa_ichigo'),
    ('himutwv'),
    ('hlinak9527'),
    ('holymolyet'),
    ('horneddeer123'),
    ('hoshinokawanao'),
    ('hoshiumi_nagisa'),
    ('hsiangvi'),
    ('huruhuruxd'),
    ('huskyun111'),
    ('huwaduck'),
    ('imjerrythewolf'),
    ('inori4723'),
    ('jack0323iijjj'),
    ('kageurakuro'),
    ('kamonegi1230'),
    ('kannazuki_miharu'),
    ('kayarina45'),
    ('keruberos523'),
    ('kevin71849'),
    ('kevindexlol'),
    ('kikishiraumi'),
    ('kri_yoruko1025'),
    ('ks85861066'),
    ('kururugiliyue_0413'),
    ('kyunekoch'),
    ('lisheng_tw'),
    ('liyin_vtuber'),
    ('liyu7611'),
    ('lorellamame'),
    ('lullaybye_v'),
    ('lusaminach'),
    ('madwolf0126'),
    ('magicglass'),
    ('manechan04'),
    ('mashiro_majo'),
    ('meowi_momiji'),
    ('millycat0908'),
    ('minami_1098'),
    ('minamoto_kenta'),
    ('mine_daa'),
    ('minto7286'),
    ('mipa_meow'),
    ('momiji72270666'),
    ('monna_1113'),
    ('moonstonemuse'),
    ('mz_fuwafuwa'),
    ('nanjinnn'),
    ('neko_ta'),
    ('nekobotaii0097'),
    ('nekohe_0104'),
    ('nekoirei0'),
    ('nekojlive'),
    ('nekolololi623'),
    ('nekomurany'),
    ('neon0414_vtuber'),
    ('nineamro'),
    ('noashizuku'),
    ('noeyinrelive'),
    ('nordifencocyt'),
    ('nycaknug'),
    ('nyfzqoq'),
    ('ouqfxxk'),
    ('pacopami'),
    ('platinach'),
    ('poppy_woolly'),
    ('portan1124'),
    ('psychemori_vtype'),
    ('qmi_uwumai0612'),
    ('r1xerdesu'),
    ('rikaantique'),
    ('riko_vtb_ch'),
    ('rinrin_farnas_1019'),
    ('ritata0501'),
    ('ruyuidesu'),
    ('sakiyamaa_'),
    ('sakura_neko_29'),
    ('sena_vtuber'),
    ('sentoyuina'),
    ('setsuna_vii'),
    ('shimesho'),
    ('shinamonkamihaza'),
    ('shingodna'),
    ('shirakabarinyun'),
    ('shiroiokamiyuzai'),
    ('siumobbb'),
    ('siuyo_'),
    ('small_925'),
    ('snowyfox_ee'),
    ('souna_vtuber'),
    ('sum1ko_vt'),
    ('sumisakura0922'),
    ('sylphygod'),
    ('takigawananaha'),
    ('tenki_vtuber'),
    ('terrorcat7414'),
    ('tiamiuuuu'),
    ('tsuki773'),
    ('tsukimiruby'),
    ('tsunek1_3akana'),
    ('tw__safetyno1'),
    ('virtualfluorite'),
    ('vtalisa'),
    ('vte04'),
    ('vtuber_amiru'),
    ('yabibibibibi'),
    ('yanran_cute'),
    ('yinuoyayudiweng'),
    ('yochorosu'),
    ('yomi44_vtuber'),
    ('yueyuhoshizora'),
    ('yukari03210'),
    ('yulelech'),
    ('zerovtuber44')
) as v(login)
where c.platform = 'twitch' and c.status = 'active' and c.external_id is null
  and lower(c.handle) = v.login;
